# Site settings
title: Paul Choi
description: Be the best data analyst.
cover: assets/images/radhakrishna.jpg
logo: assets/images/logo.png
favicon: assets/images/favicon.png
baseurl: "/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://chh-sangdall.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

# Social
facebook: facebook
twitter: twitter
github:  github

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate


# Settings for rake task
safe: False
lsi: False
username: chh-sangdall #github username
repo: chh-sangdall.github.io #github repository
branch: master #branch
relative_source: ../chh-sangdall.github.io/ #source directory
destination: ../chh-sangdall.github.io/ #destination directory
production_url:  https://samanyougarg.com/
source_url:  https://github.com/samanyougarg/hanuman #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml